package frc.robot.subsystems.operatorInterface;

public class OperatorInterfaceConstants {

    public static final int kDriverControllerPort = 0;
    public static final int kGunnerControllerPort = 1;

    public static double kLowPressureValue = 60;
    public static double kTargetPressure = 90;
    
	// these 'cutoff' values are the point at which the piecewise function
	// used for determining the output generated by the joystick input seperates
	// from a linear function to an exponential function
	// The function will be 0 from (0, 0) to (deadzone, 0)
	// Then linear from (deadzone, 0) to (cutoffX, cutoffY)
	// Then exponential from (cutoffX, cutoffY) to (1, 1)
  
    public static final double maxXDot = 8;
    public static final double maxYDot = 8;
    public static final double maxThetaDot = 3.5;
    public static final double maxAccel = 1.5;

    public static final double offset = 0;
    public static final double deadzone = .04;
    public static final double coefficient = 1;

    public static final double posError = 0.03;
    public static final double angleError = Math.toRadians(5);
    
    // The values below are using the new, modified joystick controller algorithm
    // The new algorithm does the following 
    //   zero below the deadzone
    //   linear slope from deadzone to CutOffX
    //   non-linear (depending on exponent) from CutOffX to 1.0
    
    public static final double rotationCutOffX = 0.7;
    public static final double rotationCutOffY = 0.1;
    public static final double rotationLimitY = .6;
    public static final double rotationExponent = 1;

    //nonfinal because of Shuffleboard control
    public static double translationCutOffX = 0.5;
    public static double translationCutOffY = 0.5;
    public static final double translationExponent = 1;  

}
